apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldapium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ldapium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap
      port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
    {{- if .Values.tls.enabled }}
    - name: ldaps
      port: {{ .Values.service.ldapsPort }}
      targetPort: ldaps
      protocol: TCP
    {{- end }}
  selector:
    {{- include "ldapium.selectorLabels" . | nindent 4 }}
