package httpapi

import (
	"net/http"

	"github.com/dasomel/ldapium/ui/backend/internal/config"
)

// machineOp is one entry of the static operation allowlist (D3, D13). The
// allowlist is the only thing that lets a machine principal reach an
// operation: a route absent from it is denied by the runtime guard no matter
// what the OpenAPI document or the token says. OpenAPI's machineBearer /
// x-machine-scope are generated by hand and a contract test keeps them equal
// to this table.
type machineOp struct {
	ID     string // OpenAPI operationId
	Method string
	Route  string // echo route pattern, as c.Path() reports it
	Scope  string
}

// machineOps are the 8 allowed operations of v1: GET reads only. The other 37
// protected operations (36 explicit denylist entries plus getMe) are
// deliberately not here; there is no denylist in code, only this allowlist.
var machineOps = []machineOp{
	{"listUsers", http.MethodGet, "/api/users", "directory.users.read"},
	{"listGroups", http.MethodGet, "/api/groups", "directory.groups.read"},
	{"listTree", http.MethodGet, "/api/tree", "directory.tree.read"},
	{"getEntry", http.MethodGet, "/api/entry", "directory.entry.read"},
	{"listPasswordPolicies", http.MethodGet, "/api/password-policies", "directory.policies.read"},
	{"getMonitor", http.MethodGet, "/api/monitor", "server.monitor.read"},
	// Opt-in: reachable only when a client's ceiling names the scope.
	{"listAuditActions", http.MethodGet, "/api/audit/actions", "audit.read"},
	{"getServerSettings", http.MethodGet, "/api/server-settings", "server.settings.read"},
}

var machineOpIndex = func() map[string]machineOp {
	m := make(map[string]machineOp, len(machineOps))
	for _, op := range machineOps {
		m[op.Method+" "+op.Route] = op
	}
	return m
}()

// machineOpFor is the deny-by-default lookup: ok is false for every method and
// route that is not an allowlisted GET.
func machineOpFor(method, route string) (machineOp, bool) {
	if method != http.MethodGet {
		return machineOp{}, false
	}
	op, ok := machineOpIndex[method+" "+route]
	return op, ok
}

// machineCeilings maps client id -> the scopes the server permits it (D3).
func machineCeilings(clients []config.MachineClient) map[string]map[string]bool {
	out := make(map[string]map[string]bool, len(clients))
	for _, c := range clients {
		set := make(map[string]bool, len(c.Scopes))
		for _, s := range c.Scopes {
			set[s] = true
		}
		out[c.ID] = set
	}
	return out
}

// scopeAllows resolves the effective scope: the token's scope intersected with
// the client's server-side ceiling (D3). A scope in the token but not in the
// ceiling is ignored; a scope in the ceiling but not in the token is not
// granted. A client with no ceiling entry (cannot happen after verification)
// gets nothing.
func scopeAllows(ceiling map[string]bool, tokenScopes []string, required string) bool {
	if !ceiling[required] {
		return false
	}
	for _, s := range tokenScopes {
		if s == required {
			return true
		}
	}
	return false
}
