import { test, expect } from '@playwright/test'

// This spec requires a real backend with APP_PROFILES_PATH and an allowed DN.
const identity = process.env.E2E_ADMIN_DN
const password = process.env.E2E_ADMIN_PASSWORD
if (!identity || !password) throw new Error('E2E_ADMIN_DN and E2E_ADMIN_PASSWORD are required')

test('persists a custom app profile through the UI without applying permissions', { tag: '@fixture' }, async ({ page }) => {
  await page.goto('/login')
  await page.locator('#identity').fill(identity)
  await page.locator('#password').fill(password)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/tree$/)
  await page.getByRole('link', { name: 'App SSO permissions' }).click()
  await expect(page.getByRole('heading', { name: 'Application SSO permissions' })).toBeVisible()
  const id = `custom-${Date.now()}`
  await page.getByLabel('Application ID', { exact: true }).fill(id)
  await page.getByLabel('Application name').fill('Custom example app')
  await page.getByLabel('Keycloak client ID').fill('custom-client')
  await page.getByLabel('OIDC issuer (HTTPS)').fill('https://sso.example/realms/company')
  await page.getByRole('button', { name: 'Add mapping' }).click()
  await page.getByLabel('Claim value 1', { exact: true }).fill('app-admin')
  await page.getByLabel('Application role 1', { exact: true }).fill('owner')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toContainText('Application permissions have not been applied')
  await page.reload()
  await page.getByRole('button', { name: 'Custom example app' }).click()
  await expect(page.getByLabel('Application ID', { exact: true })).toHaveValue(id)
  await expect(page.getByLabel('Claim value 1', { exact: true })).toHaveValue('app-admin')
  await expect(page.getByLabel('Application role 1', { exact: true })).toHaveValue('owner')
  await page.getByLabel('Enforcement', { exact: true }).selectOption('gateway_admission')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('alert')).toContainText('gateway admission does not enforce native application roles')
})

test('persists the selected OSS guide and exports only its supported configuration', { tag: '@fixture' }, async ({ page }) => {
  await page.goto('/login')
  await page.locator('#identity').fill(identity!)
  await page.locator('#password').fill(password!)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/tree$/)
  await page.getByRole('link', { name: 'App SSO permissions' }).click()
  await page.getByRole('button', { name: 'Harbor', exact: false }).click()
  await expect(page.getByText('OIDC Admin Group grants system administration.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Grafana', exact: false }).click()
  await expect(page.getByLabel('Token source')).toHaveValue('id_token')
  const id = `grafana-${Date.now()}`
  await page.getByLabel('Application ID', { exact: true }).fill(id)
  await page.getByLabel('Application name').fill('Grafana UI example')
  await page.getByLabel('Keycloak client ID').fill('grafana-ui')
  await page.getByLabel('OIDC issuer (HTTPS)').fill('https://sso.example/realms/company')
  await page.getByRole('button', { name: 'Add mapping' }).click()
  await page.getByLabel('Claim value 1', { exact: true }).fill('developers')
  await page.getByLabel('Application role 1', { exact: true }).selectOption('Editor')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toContainText('Application permissions have not been applied')
  await page.reload()
  await page.getByRole('button', { name: 'Grafana UI example', exact: false }).click()
  await expect(page.getByRole('button', { name: 'Grafana Configuration export', exact: false })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('tab', { name: 'Export and verify' }).click()
  await expect(page.getByLabel('Configuration format')).toHaveValue('grafana')
  await page.getByLabel('Claim values (semicolon separated)').fill('developers; unknown')
  await page.getByRole('button', { name: 'Preview mapping' }).click()
  await expect(page.getByText('Editor', { exact: true })).toBeVisible()
  await expect(page.getByText('unknown', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Export configuration' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download file' }).click()
  expect((await download).suggestedFilename()).toBe(`${id}-grafana-settings.json`)
  await page.getByRole('tab', { name: 'App and claims' }).click()
  await page.getByRole('button', { name: 'Harbor Native setup guide', exact: false }).click()
  await expect(page.getByRole('tab', { name: 'Export and verify' })).toBeDisabled()
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toContainText('Application permissions have not been applied')
  await page.getByRole('tab', { name: 'Export and verify' }).click()
  await expect(page.getByLabel('Configuration format')).toHaveValue('generic')
  await expect(page.getByLabel('Configuration format').locator('option')).toHaveCount(1)
})

test('creates and reuses a custom integration method outside the built-in OSS catalog', { tag: '@fixture' }, async ({ page }) => {
  await page.goto('/login')
  await page.locator('#identity').fill(identity!)
  await page.locator('#password').fill(password!)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/tree$/)
  await page.getByRole('link', { name: 'App SSO permissions' }).click()
  await page.getByRole('button', { name: 'Add / manage methods' }).click()
  const methodID = `custom-analytics-${Date.now()}`
  await page.getByLabel('Method ID (custom- prefix)').fill(methodID)
  await page.getByLabel('Method name', { exact: true }).fill('Analytics custom method')
  await page.getByLabel('Method summary').fill('Claim roles to workspace access')
  await page.getByLabel('Permission scope and limits').fill('Workspace authorization must be configured in the app')
  await page.getByLabel('Documentation URL (HTTPS)').fill('https://docs.example/analytics')
  await page.getByLabel('Default claim path').fill('app_roles')
  await page.getByLabel('Default token source').selectOption('userinfo')
  await page.getByLabel('Native roles').fill('reader\nowner')
  await page.getByLabel('Setup steps').fill('Register the OIDC client\nConfigure workspace roles')
  await page.getByRole('button', { name: 'Save method', exact: true }).click()
  await page.getByRole('button', { name: 'Analytics custom method Custom method', exact: false }).click()
  await expect(page.getByLabel('Role claim path')).toHaveValue('app_roles')
  await expect(page.getByLabel('Token source', { exact: true })).toHaveValue('userinfo')
  const id = `analytics-${Date.now()}`
  await page.getByLabel('Application ID', { exact: true }).fill(id)
  await page.getByLabel('Application name', { exact: true }).fill('Custom analytics instance')
  await page.getByLabel('Keycloak client ID').fill('analytics-client')
  await page.getByLabel('OIDC issuer (HTTPS)').fill('https://sso.example/realms/company')
  await page.getByRole('button', { name: 'Add mapping' }).click()
  await page.getByLabel('Claim value 1', { exact: true }).fill('analysts')
  await page.getByLabel('Application role 1', { exact: true }).selectOption('reader')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toContainText('Application permissions have not been applied')
  await page.reload()
  await page.getByRole('button', { name: 'Custom analytics instance', exact: false }).click()
  await expect(page.getByRole('button', { name: 'Analytics custom method Custom method', exact: false })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('Application role 1', { exact: true })).toHaveValue('reader')
  await page.getByRole('tab', { name: 'Export and verify' }).click()
  await expect(page.getByLabel('Configuration format').locator('option')).toHaveCount(1)
  await page.getByRole('tab', { name: 'App and claims' }).click()
  await page.getByRole('button', { name: 'Add / manage methods' }).click()
  await page.getByLabel('Method to edit').selectOption(methodID)
  await expect(page.getByLabel('Method ID (custom- prefix)')).toBeDisabled()
  await page.getByLabel('Method summary').fill('Updated reusable method')
  await page.getByRole('button', { name: 'Save method', exact: true }).click()
  await expect(page.getByText('Updated reusable method', { exact: true })).toBeVisible()
})
