#!/usr/bin/env bash
# Identity-lifecycle load profile (issue #124, AC absorbed from #19): measure
# joiner / mover / leaver operations over the real LDAP wire against a
# container pre-loaded with N identities.
#
#   ./scripts/bench-lifecycle.sh --identities 1000000 --ops 100000 \
#       --out scripts/bench-results --label "colima aarch64 VM, 3 vCPU/6 GiB cap"
#   ./scripts/bench-lifecycle.sh --identities 20000 --ops 2000 --out /tmp/bench-out
#
# Reuses rather than duplicates: the base load is scripts/bench-load.sh
# itself (same offline-slapadd-over-a-bootstrapped-cn=config path, same
# generator, same named volumes — see that script's own header for why
# offline, not LDAP_SEED_DIR), and the operation queue is generated by the
# pure, separately-testable scripts/bench-generate-lifecycle-ops.py. This
# script's own job is only the third phase: run that queue's joiner/mover/
# leaver operations over the wire against a real running server, and report.
#
# Lifecycle semantics mirror ui/backend/internal/ldapclient exactly, not a
# reinterpretation of them:
#   - mover:  ModifyDN with newSuperior, RDN preserved, deleteOldRDN=true
#             (tree.go buildMoveRequest) -> `ldapmodrdn -r -s <newSuperior>`.
#   - leaver: deactivate (replace pwdAccountLockedTime with ppolicy's
#             "locked indefinitely" sentinel, users.go lockModify) then
#             delete -> `ldapmodify` (replace) then `ldapdelete`.
#   - joiner: add a new uid=join-<i> entry under ou=people — not mirrored
#             from a specific backend method (there is no dedicated
#             "create identity" RPC to mirror; this is a plain ldapadd of
#             the same inetOrgPerson shape bench-generate-ldif.py uses).
#
# Movers target ou=people-moved,<base> (created once, up front) rather than
# each other or back into ou=people, so a run is safe to inspect afterward
# without the moved entries colliding with the next run's fresh load.
#
# ppolicy: this chart's ppolicy overlay module is loaded unconditionally in
# image/ldifs/01-cn-config.ldif regardless of LDAP_PASSWORD_POLICY_ENABLED
# (only the pwdPolicy entry olcPPolicyDefault points at is conditional on
# that flag) — confirmed by reading that file, not assumed — so
# pwdAccountLockedTime is legal schema on every stock ldapium:e2e/-chaos/
# -security image whether or not LDAP_PASSWORD_POLICY_ENABLED is set.
# Detected anyway, not hardcoded, via a cn=config search below: a custom
# --image without the overlay compiled in skips the deactivate step and
# leaver becomes delete-only, and the report says so.
#
# Timeout model deliberately does NOT use the `timeout` binary applied
# elsewhere in this repo's CI-only shell: it is not installed by default on
# macOS (this benchmark's other required local-run target, per AGENTS.md),
# unlike GNU coreutils' `date +%N` which macOS 15+ now ships natively. A
# cooperative deadline check between operations (not preemptive mid-command
# kill) keeps this portable; see run_worker below.
set -euo pipefail

image=""
identities=0
ops=0
concurrency=4
mix="50:30:20"
base="dc=example,dc=org"
out_dir=""
db_max_size_gb=0
timeout_seconds=0
label=""
keep_volumes=0

is_uint() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
    *) return 0 ;;
  esac
}

usage() {
  cat <<'EOF'
Usage: bench-lifecycle.sh --identities N --ops M --out DIR [options]

  --identities           N synthetic identities to generate and load as the
                          base population (required)
  --ops                  M lifecycle operations to run against the loaded
                          base (required)
  --out                  directory to write bench-lifecycle-<N>-<M>-<ts>.json/.md
                          (required)
  --concurrency          parallel LDAP client workers (default 4)
  --mix                  joiner:mover:leaver ratio (default 50:30:20) —
                          mover+leaver counts derived from this and --ops
                          must not exceed --identities (movers/leavers pick
                          disjoint identities, they never race each other)
  --image                ldapium image to benchmark (default: ldapium:e2e)
  --base                 base DN (default dc=example,dc=org)
  --db-max-size-gb       olcDbMaxSize, GiB, forwarded to bench-load.sh.
                          Default: same sizing formula as bench-profile.sh
                          (~9400 bytes/entry, see that script's header for
                          why) — pass this explicitly, sized from a measured
                          run at a nearby scale, for anything beyond a
                          quick smoke test.
  --timeout-seconds      wall-clock cap on the OPERATIONS phase only (base
                          load has no cap here — use bench-load.sh directly
                          if that needs bounding). 0 (default) means
                          unbounded. Cooperative: a worker finishes its
                          current operation, then stops if the deadline has
                          passed. On expiry, status is "timed-out" and
                          sanity checks are skipped.
  --label                free-text environment label recorded in the report
  --keep-volumes         do not delete the load's config/data volumes at
                          the end (default: delete them — this runner is
                          meant to be a self-contained one-shot, unlike
                          bench-load.sh which leaves volumes for a separate
                          bench-search.sh)
  -h, --help             this text
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --image) image="${2:?}"; shift 2 ;;
    --identities)
      if ! is_uint "${2:-}" || [ "${2:-0}" -le 0 ]; then
        printf -- '--identities must be a positive integer (got: %s)\n\n' "${2:-}" >&2
        usage >&2; exit 2
      fi
      identities="${2:?}"; shift 2 ;;
    --ops)
      if ! is_uint "${2:-}" || [ "${2:-0}" -le 0 ]; then
        printf -- '--ops must be a positive integer (got: %s)\n\n' "${2:-}" >&2
        usage >&2; exit 2
      fi
      ops="${2:?}"; shift 2 ;;
    --concurrency)
      if ! is_uint "${2:-}" || [ "${2:-0}" -le 0 ]; then
        printf -- '--concurrency must be a positive integer (got: %s)\n\n' "${2:-}" >&2
        usage >&2; exit 2
      fi
      concurrency="${2:?}"; shift 2 ;;
    --mix)
      case "${2:-}" in
        [0-9]*:[0-9]*:[0-9]*) : ;;
        *)
          printf -- '--mix must be J:M:L with non-negative integers (got: %s)\n\n' "${2:-}" >&2
          usage >&2; exit 2 ;;
      esac
      mix="${2:?}"; shift 2 ;;
    --base) base="${2:?}"; shift 2 ;;
    --out) out_dir="${2:?}"; shift 2 ;;
    --db-max-size-gb) db_max_size_gb="${2:?}"; shift 2 ;;
    --timeout-seconds)
      is_uint "${2:-}" || {
        printf -- '--timeout-seconds must be a non-negative integer (got: %s)\n\n' "${2:-}" >&2
        usage >&2; exit 2
      }
      timeout_seconds="${2:?}"; shift 2 ;;
    --label) label="${2:?}"; shift 2 ;;
    --keep-volumes) keep_volumes=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown argument: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

image="${image:-ldapium:e2e}"
[ "$identities" -gt 0 ] 2>/dev/null || { echo "--identities is required" >&2; usage >&2; exit 2; }
[ "$ops" -gt 0 ] 2>/dev/null || { echo "--ops is required" >&2; usage >&2; exit 2; }
[ -n "$out_dir" ] || { echo "--out is required" >&2; usage >&2; exit 2; }

command -v docker >/dev/null 2>&1 || { echo "docker not found on PATH" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "python3 not found on PATH" >&2; exit 1; }
[ "$(date +%N)" != "N" ] || { echo "date +%N unsupported — need macOS 15+ or GNU coreutils date" >&2; exit 1; }

script_dir="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$out_dir"

# Same formula and rationale as bench-profile.sh's own db_max_size_gb
# default (see that script's header comment for the two live-verified
# undersizing failures behind these constants) — the loaded base here is
# generated by the identical bench-generate-ldif.py, so the same per-entry
# footprint applies.
if [ "$db_max_size_gb" -le 0 ] 2>/dev/null; then
  db_max_size_gb=$(awk -v n="$identities" 'BEGIN{gb=(n*4700*2.0)/1073741824; v=int(gb)+1; if (v<1) v=1; print v}')
fi

# Op counts + queue are computed once, up front, so a --mix/--identities
# combination that can't produce disjoint mover+leaver targets fails fast
# (exit 2, no containers started) rather than after paying for a load.
ts="$(date -u +%Y%m%dT%H%M%SZ)"
run_id="ldapium-benchlifecycle-${identities}-${ops}"
work_dir=$(mktemp -d "${TMPDIR:-/tmp}/${run_id}-work-XXXXXX")
ops_file="${work_dir}/ops.tsv"
python3 "${script_dir}/bench-generate-lifecycle-ops.py" \
  --identities "$identities" --ops "$ops" --mix "$mix" > "$ops_file" || {
  rm -rf "$work_dir"; exit 2
}
counts_line=$(head -1 "$ops_file")
joiner_count=$(printf '%s' "$counts_line" | awk -F'\t' '{print $2}')
mover_count=$(printf '%s' "$counts_line" | awk -F'\t' '{print $3}')
leaver_count=$(printf '%s' "$counts_line" | awk -F'\t' '{print $4}')
tail -n +2 "$ops_file" > "${ops_file}.body"

log() { printf '%s %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
log "op mix resolved: joiner=${joiner_count} mover=${mover_count} leaver=${leaver_count} (requested ${ops}, ratio ${mix})"

cleanup() {
  docker rm -f "${run_id}-server" >/dev/null 2>&1 || true
  rm -rf "$work_dir"
  if [ "$keep_volumes" -eq 0 ] && [ -n "${vol_config:-}" ] && [ -n "${vol_data:-}" ]; then
    docker volume rm "$vol_config" "$vol_data" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

### 1. Base load (delegated to bench-load.sh) ---------------------------------
load_json="${work_dir}/load.json"
# A clean run every time, same reasoning as bench-profile.sh: reusing
# leftover volumes from a previous invocation at the same --identities would
# make loadedCount / the uid-index assumptions below silently wrong instead
# of failing loudly.
docker volume rm "ldapium-bench-${identities}-config" "ldapium-bench-${identities}-data" >/dev/null 2>&1 || true
log "loading ${identities} base identities (bench-load.sh)..."
load_status="ok"
"${script_dir}/bench-load.sh" --image "$image" --count "$identities" --base "$base" \
  --db-max-size-gb "$db_max_size_gb" --json "$load_json" >&2 || load_status="failed"

jfield() {
  python3 -c '
import json, sys
try:
    d = json.load(open(sys.argv[2]))
    print(d.get(sys.argv[1], "n/a"))
except Exception:
    print("n/a")
' "$1" "$2"
}

vol_config=$(jfield configVolume "$load_json")
vol_data=$(jfield dataVolume "$load_json")
loaded_count=$(jfield loadedCount "$load_json")
load_seconds=$(jfield loadSeconds "$load_json")

status="$load_status"
ppolicy_detected=0
sanity_json="{}"
kinds_json="{}"
executed=0
error_count=0
overall_ops_per_sec=0
timed_out=0

if [ "$status" = "ok" ]; then
  ### 2. Server + fixtures -----------------------------------------------------
  log "starting server against the loaded volumes..."
  docker run -d --name "${run_id}-server" --cpus 3 --memory 6g \
    -v "${vol_config}:/etc/openldap/slapd.d" \
    -v "${vol_data}:/var/lib/openldap/data" \
    -e LDAP_ADMIN_PASSWORD=bench-not-a-real-secret \
    -e LDAP_ROOT_DN="$base" \
    "$image" >/dev/null
  ready=0
  for _ in $(seq 1 60); do
    docker exec "${run_id}-server" ldapwhoami -x -D "cn=admin,${base}" -w bench-not-a-real-secret >/dev/null 2>&1 && { ready=1; break; }
    sleep 1
  done
  [ "$ready" -eq 1 ] || { log "server never became ready"; docker logs "${run_id}-server" >&2; status="server-failed"; }
fi

if [ "$status" = "ok" ]; then
  # cn=config admin reuses the same password as the data admin (see
  # image/ldifs/02-cn-config-admin.ldif's own comment) — a plain search for
  # the ppolicy overlay entry, not an assumption from LDAP_PASSWORD_POLICY_ENABLED,
  # since that env var only gates olcPPolicyDefault, not the overlay module
  # itself (see this script's header).
  # Retried, not a single shot: live-verified this occasionally misses on
  # the very first query right after the "ready" whoami check passes — the
  # main mdb backend and the cn=config backend don't necessarily finish
  # coming up in the same instant, and whoami above only proves the former.
  # A false "not detected" would silently downgrade every leaver op to
  # delete-only on a real ppolicy-enabled image, so this retries rather than
  # trusting one query.
  ppolicy_detected=0
  for _ in $(seq 1 5); do
    if docker exec "${run_id}-server" ldapsearch -x -D "cn=admin,cn=config" -w bench-not-a-real-secret \
        -b cn=config -LLL '(olcOverlay=ppolicy)' dn 2>/dev/null | grep -q '^dn:'; then
      ppolicy_detected=1
      break
    fi
    sleep 1
  done
  if [ "$ppolicy_detected" -eq 1 ]; then
    log "ppolicy overlay detected — leaver ops will deactivate (lock) then delete"
  else
    log "ppolicy overlay NOT detected on this image — leaver ops will delete only, no deactivate step"
  fi

  create_moved_ou="dn: ou=people-moved,${base}
objectClass: organizationalUnit
ou: people-moved
"
  printf '%s' "$create_moved_ou" | docker exec -i "${run_id}-server" \
    ldapadd -x -D "cn=admin,${base}" -w bench-not-a-real-secret >/dev/null 2>&1 \
    || { log "failed to create ou=people-moved,${base}"; status="server-failed"; }
fi

### 3. Lifecycle operations ----------------------------------------------------
if [ "$status" = "ok" ]; then
  results_dir="${work_dir}/results"
  mkdir -p "$results_dir"
  deadline=0
  [ "$timeout_seconds" -gt 0 ] && deadline=$(awk -v now="$(date +%s.%N)" -v t="$timeout_seconds" 'BEGIN{print now+t}')
  stopped_early_file="${work_dir}/stopped-early"
  : > "$stopped_early_file"

  run_worker() {
    local wid="$1" out server n kind arg now rc t0 t1 ms entry_ldif uid lock_ldif
    out="${results_dir}/${wid}.tsv"
    : > "$out"
    server="${run_id}-server"
    n=0
    while IFS=$'\t' read -r kind arg; do
      n=$((n + 1))
      [ $(( (n - 1) % concurrency )) -eq $((wid - 1)) ] || continue
      if [ "$deadline" != "0" ]; then
        now=$(date +%s.%N)
        if awk -v now="$now" -v d="$deadline" 'BEGIN{exit !(now>=d)}'; then
          echo 1 >> "$stopped_early_file"
          break
        fi
      fi
      rc=0
      t0=$(date +%s.%N)
      case "$kind" in
        joiner)
          entry_ldif="dn: uid=join-${arg},ou=people,${base}
objectClass: inetOrgPerson
uid: join-${arg}
cn: Join User ${arg}
sn: JoinUser${arg}
givenName: Join${arg}
mail: join-${arg}@bench.invalid
employeeType: dept0000
"
          printf '%s' "$entry_ldif" | docker exec -i "$server" \
            ldapadd -x -D "cn=admin,${base}" -w bench-not-a-real-secret >/dev/null 2>&1 || rc=$?
          ;;
        mover)
          uid=$(printf 'bench%09d' "$arg")
          docker exec "$server" ldapmodrdn -x -D "cn=admin,${base}" -w bench-not-a-real-secret \
            -r -s "ou=people-moved,${base}" "uid=${uid},ou=people,${base}" "uid=${uid}" \
            >/dev/null 2>&1 || rc=$?
          ;;
        leaver)
          uid=$(printf 'bench%09d' "$arg")
          if [ "$ppolicy_detected" -eq 1 ]; then
            lock_ldif="dn: uid=${uid},ou=people,${base}
changetype: modify
replace: pwdAccountLockedTime
pwdAccountLockedTime: 000001010000Z
"
            printf '%s' "$lock_ldif" | docker exec -i "$server" \
              ldapmodify -x -D "cn=admin,${base}" -w bench-not-a-real-secret >/dev/null 2>&1 || rc=$?
          fi
          docker exec "$server" ldapdelete -x -D "cn=admin,${base}" -w bench-not-a-real-secret \
            "uid=${uid},ou=people,${base}" >/dev/null 2>&1 || rc=$?
          ;;
      esac
      t1=$(date +%s.%N)
      ms=$(awk -v a="$t0" -v b="$t1" 'BEGIN{printf "%.3f", (b-a)*1000}')
      printf '%s\t%s\t%s\n' "$kind" "$ms" "$rc" >> "$out"
    done < "${ops_file}.body"
  }

  log "running ${concurrency} workers over ${ops} operations..."
  ops_start=$(date +%s.%N)
  pids=()
  for w in $(seq 1 "$concurrency"); do
    run_worker "$w" &
    pids+=($!)
  done
  for pid in "${pids[@]}"; do
    wait "$pid"
  done
  ops_end=$(date +%s.%N)
  ops_seconds=$(awk -v a="$ops_start" -v b="$ops_end" 'BEGIN{printf "%.3f", b-a}')

  cat "${results_dir}"/*.tsv > "${results_dir}/all.tsv" 2>/dev/null || : > "${results_dir}/all.tsv"
  executed=$(wc -l < "${results_dir}/all.tsv" | tr -d ' ')
  error_count=$(awk -F'\t' '$3 != 0' "${results_dir}/all.tsv" | wc -l | tr -d ' ')
  overall_ops_per_sec=$(awk -v n="$executed" -v s="$ops_seconds" 'BEGIN{printf "%.2f", (s>0)?n/s:0}')
  [ -s "$stopped_early_file" ] && timed_out=1

  percentile() {
    local file="$1" p="$2" n idx
    n=$(wc -l < "$file" | tr -d ' ')
    [ "$n" -gt 0 ] || { echo 0; return; }
    idx=$(awk -v n="$n" -v p="$p" 'BEGIN{x=(p/100)*n; i=int(x); if (x>i) i++; if (i<1) i=1; if (i>n) i=n; print i}')
    sed -n "${idx}p" "$file"
  }

  kinds_json="{"
  first=1
  for kind in joiner mover leaver; do
    kind_file="${results_dir}/${kind}.sorted"
    awk -F'\t' -v k="$kind" '$1==k{print $2}' "${results_dir}/all.tsv" | sort -n > "$kind_file"
    kcount=$(wc -l < "$kind_file" | tr -d ' ')
    kfailed=$(awk -F'\t' -v k="$kind" '$1==k && $3!=0' "${results_dir}/all.tsv" | wc -l | tr -d ' ')
    kp50=$(percentile "$kind_file" 50); kp95=$(percentile "$kind_file" 95); kp99=$(percentile "$kind_file" 99)
    kqps=$(awk -v n="$kcount" -v s="$ops_seconds" 'BEGIN{printf "%.2f", (s>0)?n/s:0}')
    [ "$first" -eq 1 ] || kinds_json="${kinds_json},"
    first=0
    kinds_json="${kinds_json}\"${kind}\":{\"count\":${kcount},\"failed\":${kfailed},\"opsPerSecond\":${kqps},\"latencyMsP50\":${kp50},\"latencyMsP95\":${kp95},\"latencyMsP99\":${kp99}}"
  done
  kinds_json="${kinds_json}}"

  if [ "$timed_out" -eq 1 ]; then
    status="timed-out"
  elif [ "$error_count" -gt 0 ]; then
    status="failed"
  fi

  ### 4. Sanity checks (skipped on timeout — see bench-profile.sh's own
  ### precedent of skipping downstream phases on a non-ok upstream status) ---
  if [ "$status" != "timed-out" ]; then
    log "running post-run sanity checks..."
    moved_actual=$(docker exec "${run_id}-server" ldapsearch -x -D "cn=admin,${base}" -w bench-not-a-real-secret \
      -b "ou=people-moved,${base}" -LLL '(uid=bench*)' uid 2>/dev/null | grep -c '^uid:' || true)
    joiner_actual=$(docker exec "${run_id}-server" ldapsearch -x -D "cn=admin,${base}" -w bench-not-a-real-secret \
      -b "ou=people,${base}" -LLL '(uid=join-*)' uid 2>/dev/null | grep -c '^uid:' || true)
    remaining_bench=$(docker exec "${run_id}-server" ldapsearch -x -D "cn=admin,${base}" -w bench-not-a-real-secret \
      -b "ou=people,${base}" -LLL '(uid=bench*)' uid 2>/dev/null | grep -c '^uid:' || true)
    remaining_expected=$((identities - mover_count - leaver_count))

    moved_ok=$([ "$moved_actual" = "$mover_count" ] && echo true || echo false)
    joiner_ok=$([ "$joiner_actual" = "$joiner_count" ] && echo true || echo false)
    leaver_ok=$([ "$remaining_bench" = "$remaining_expected" ] && echo true || echo false)

    sanity_json="{\"moversInMovedOu\":{\"expected\":${mover_count},\"actual\":${moved_actual},\"ok\":${moved_ok}},\"joinersExist\":{\"expected\":${joiner_count},\"actual\":${joiner_actual},\"ok\":${joiner_ok}},\"remainingAfterLeavers\":{\"expected\":${remaining_expected},\"actual\":${remaining_bench},\"ok\":${leaver_ok}}}"

    if [ "$moved_ok" != "true" ] || [ "$joiner_ok" != "true" ] || [ "$leaver_ok" != "true" ]; then
      log "sanity check FAILED: ${sanity_json}"
      status="failed"
    else
      log "sanity checks passed"
    fi
  else
    log "timed out before completing the operation queue — skipping sanity checks"
  fi
else
  ops_seconds=0
fi

### 5. Report -------------------------------------------------------------------
out_base="${out_dir}/bench-lifecycle-${identities}-${ops}-${ts}"
json_file="${out_base}.json"
md_file="${out_base}.md"

label_json=$(printf '%s' "$label" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')
cat > "$json_file" <<JSON
{
  "benchmark": "lifecycle",
  "label": ${label_json},
  "timestampUtc": "${ts}",
  "requestedIdentities": ${identities},
  "requestedOps": ${ops},
  "mix": "${mix}",
  "concurrency": ${concurrency},
  "status": "${status}",
  "ppolicyDetected": $([ "$ppolicy_detected" -eq 1 ] && echo true || echo false),
  "load": {"loadedCount": ${loaded_count}, "loadSeconds": ${load_seconds}, "status": "${load_status}"},
  "opCounts": {"joiner": ${joiner_count}, "mover": ${mover_count}, "leaver": ${leaver_count}},
  "executed": ${executed},
  "errorCount": ${error_count},
  "wallSeconds": ${ops_seconds},
  "overallOpsPerSecond": ${overall_ops_per_sec},
  "byKind": ${kinds_json},
  "sanity": ${sanity_json}
}
JSON
python3 -m json.tool "$json_file" > "${json_file}.pretty" && mv "${json_file}.pretty" "$json_file"

{
  echo "# Identity-lifecycle benchmark: ${identities} identities, ${ops} ops"
  echo
  echo "- Label: ${label:-none}"
  echo "- Timestamp (UTC): ${ts}"
  echo "- Image: ${image}"
  echo "- Mix: ${mix} (joiner=${joiner_count} mover=${mover_count} leaver=${leaver_count})"
  echo "- Concurrency: ${concurrency}"
  echo "- ppolicy overlay detected: ${ppolicy_detected}"
  echo "- Status: **${status}**"
  echo
  echo "| Metric | Value |"
  echo "|---|---|"
  echo "| Loaded identities | ${loaded_count} / ${identities} |"
  echo "| Operations executed | ${executed} / ${ops} |"
  echo "| Errors | ${error_count} |"
  echo "| Wall time (ops phase) | ${ops_seconds}s |"
  echo "| Overall throughput | ${overall_ops_per_sec} ops/s |"
  if [ "$kinds_json" != "{}" ]; then
    for kind in joiner mover leaver; do
      cnt=$(printf '%s' "$kinds_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('${kind}',{}).get('count','n/a'))")
      p50=$(printf '%s' "$kinds_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('${kind}',{}).get('latencyMsP50','n/a'))")
      p95=$(printf '%s' "$kinds_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('${kind}',{}).get('latencyMsP95','n/a'))")
      p99=$(printf '%s' "$kinds_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('${kind}',{}).get('latencyMsP99','n/a'))")
      echo "| ${kind} count / p50 / p95 / p99 | ${cnt} / ${p50}ms / ${p95}ms / ${p99}ms |"
    done
  fi
  echo
  echo "Sanity checks: \`${sanity_json}\`"
  echo
  echo "Full machine-readable record: \`$(basename "$json_file")\`"
} > "$md_file"

log "report written: ${json_file} / ${md_file}"
cat "$json_file"

[ "$status" = "ok" ]
