#!/usr/bin/env bash
# Third-party licence inventory and allow-list gate.
#
#   ./scripts/licenses.sh          regenerate THIRD-PARTY-LICENSES.md
#   ./scripts/licenses.sh --check  verify it is current, and that every
#                                  dependency is on the allow-list (CI)
#
# The allow-list is permissive-only on purpose. This project is Apache-2.0 and
# is meant to drop into commercial deployments; a copyleft dependency arriving
# through a transitive bump should stop a build, not be discovered later by
# somebody's legal review.
#
# Not covered here: what the server image compiles (OpenLDAP, from the pinned
# upstream tarball) and the Debian base packages. Those are inventoried by the
# SBOM the release workflow attaches to each image, and attributed in NOTICE.
set -euo pipefail

cd "$(dirname "$0")/.."

OUTPUT=THIRD-PARTY-LICENSES.md
GO_ALLOWED="MIT,Apache-2.0,BSD-3-Clause,BSD-2-Clause,ISC"
NPM_ALLOWED="MIT;Apache-2.0;BSD-3-Clause;BSD-2-Clause;ISC;0BSD;CC0-1.0;Unlicense"
OPENLDAP_VERSION=$(awk -F= '/^ARG OPENLDAP_VERSION=/ { print $2; exit }' image/Dockerfile)

check=0
[ "${1:-}" = "--check" ] && check=1

need() {
	command -v "$1" >/dev/null 2>&1 || {
		echo "$1 is required; $2" >&2
		exit 2
	}
}
need go "install Go"
need npx "install Node"

go_licenses() {
	if command -v go-licenses >/dev/null 2>&1; then
		go-licenses "$@"
	else
		go run github.com/google/go-licenses@v1.6.0 "$@"
	fi
}

# go-licenses reports this repo's own packages as Unknown (the LICENSE lives at
# the repo root, above the Go module), so they are excluded rather than
# silencing Unknown in general — an actually unknown dependency must still fail.
go_csv=$(cd ui/backend && go_licenses csv ./... 2>/dev/null | grep -v '^github.com/dasomel/ldapium' | sort)
npm_csv=$(cd ui/frontend && npx --yes license-checker-rseidelsohn@5.0.1 \
	--production --excludePrivatePackages --csv --nopeer 2>/dev/null | tail -n +2 | sort)

{
	cat <<EOF
# Third-party licenses

Everything the published artifacts depend on, and under what licence. This
file is generated by \`scripts/licenses.sh\`; CI regenerates it and fails if
the committed copy is out of date or a dependency arrives under a licence
that is not on the allow-list.

No component below is copyleft, deliberately: this project is Apache-2.0 and
is meant to be deployable commercially without obligations beyond attribution.

## Bundled in the server image

The image compiles OpenLDAP from the upstream source release and ships it
unmodified. See [NOTICE](NOTICE) and
[docs/OPENLDAP-PUBLIC-LICENSE-2.8.txt](docs/OPENLDAP-PUBLIC-LICENSE-2.8.txt).

| Component | Version | License |
|---|---|---|
| OpenLDAP Software | ${OPENLDAP_VERSION} | OpenLDAP Public License 2.8 |
| Debian base (\`debian:trixie-slim\`) | rolling | Various; redistributed unmodified |
| OpenSSL, Cyrus SASL, libargon2 | as packaged by Debian | Apache-2.0 / BSD-style / CC0-1.0 |

The Debian layer is used as an operating system rather than linked into this
project's code, and its packages are redistributed unmodified — the ordinary
container-base arrangement. Their licence files stay in place inside the image
under \`/usr/share/doc/\`. For the exact package list of a given image, use the
SBOM attached to that release, or:

    syft ghcr.io/dasomel/ldapium:<release> -o spdx-json

## UI backend (Go)

| Module | License | Source |
|---|---|---|
EOF
	printf '%s\n' "$go_csv" | awk -F, '{ printf "| `%s` | %s | [link](%s) |\n", $1, $3, $2 }'

	cat <<'EOF'

## UI frontend (npm, production dependencies)

| Package | License |
|---|---|
EOF
	printf '%s\n' "$npm_csv" | tr -d '"' | awk -F, '{ printf "| `%s` | %s |\n", $1, $3 }'

	cat <<'EOF'

Development-only dependencies (Vite, TypeScript, oxlint, Tailwind's build
tooling) are absent because they are not part of any published artifact. CI
holds them to the same allow-list regardless.
EOF
} >"${OUTPUT}.new"

if [ "$check" -eq 1 ]; then
	echo "checking Go dependency licences against: $GO_ALLOWED"
	(cd ui/backend && go_licenses check ./... \
		--allowed_licenses="$GO_ALLOWED" \
		--ignore github.com/dasomel/ldapium)

	echo "checking npm dependency licences against: $NPM_ALLOWED"
	(cd ui/frontend && npx --yes license-checker-rseidelsohn@5.0.1 \
		--production --excludePrivatePackages --onlyAllow "$NPM_ALLOWED" --summary)

	if ! diff -u "$OUTPUT" "${OUTPUT}.new"; then
		rm -f "${OUTPUT}.new"
		echo
		echo "::error::$OUTPUT is out of date — run ./scripts/licenses.sh and commit the result" >&2
		exit 1
	fi
	rm -f "${OUTPUT}.new"
	echo "$OUTPUT is current and every licence is allowed"
else
	mv "${OUTPUT}.new" "$OUTPUT"
	echo "wrote $OUTPUT"
fi
